describe('Editar tag', () => {
  it('Se crea un tag desde el inicio de sesión hasta la finalización de la creación', () => {
    cy.visit(configJson.host)
    cy.wait(5000)
    cy.get('input[name="identification"]').type(configJson.user)
    cy.wait(2000)
    cy.get('input[name="password"]').type(configJson.password)
    cy.wait(2000)
    cy.get('button[class="login gh-btn gh-btn-blue gh-btn-block gh-btn-icon ember-view"]').click()
    cy.wait(2000)
    cy.get('a[href="#/tags/"]').click()
    cy.wait(2000)
    cy.get('a[href="#/tags/new/"]').click()
    cy.wait(5000)
    cy.get('#tag-name').type('Tag')
    cy.wait(5000)
    cy.get('#tag-description').type('Se edita un tag de prueba para validar la funcionalidad')
    cy.wait(5000)
    cy.get('button[class="gh-btn gh-btn-blue gh-btn-icon ember-view"]').click()
    cy.wait(5000)
    cy.get('a[href="#/tags/"][data-cypress-el="true"]').click()
    cy.wait(5000)
    cy.contains('h3', 'Tag').click()
    cy.wait(5000)
    cy.get('#tag-name').type('Tag')
    cy.wait(5000)
    cy.get('#tag-description').type('Se edita un tag de prueba para validar la funcionalidad')
    cy.wait(5000)
    cy.get('button[class="gh-btn gh-btn-blue gh-btn-icon ember-view"]').click()
    cy.wait(5000)
    cy.get('a[href="#/tags/"][data-cypress-el="true"]').click()
    cy.wait(5000)
    cy.get("p.gh-tag-list-description").contains("edita").should('exist');
  })
})