describe('invitar usuario', () => {
    it('Se hace invitacion a un usuario', () => {
      cy.visit('http://localhost:2368/ghost')
      cy.wait(2000)
      cy.get('input[name="identification"]').type('pruebasautomatizadas@uniandes.edu.co')
      cy.wait(2000)
      cy.get('input[name="password"]').type('pruebasautomatizadas')
      cy.wait(2000)
      cy.get('button[class="login gh-btn gh-btn-blue gh-btn-block gh-btn-icon ember-view"]').click()
      cy.wait(2000)
      cy.get('a[href="#/staff/"][class="ember-view"]').click()
      cy.wait(2000)
      cy.get('button[class="gh-btn gh-btn-green"]').click()
      cy.wait(5000)
      cy.get('input[name="email"]').type('prueba@prueba.com')
      cy.wait(2000)
      cy.get('button[class="gh-btn gh-btn-green gh-btn-icon ember-view"]').click()
      cy.wait(2000)
      cy.reload()
    })
})